### ISSUE TITLE
GeneaProve could not import your file: None

### ISSUE THREAD

**Issue by oriste** [briot/geneapro#20]
Hi, I'm trying to import a gedcom file that has been generated by Reunion on OS X. There were many tags not recognised which I removed. Finally all tags left passed and I got the following message:

"GeneaProve could not import your file. This is either because your file does not contain correct GEDCOM data, or more likely because of limitations in GeneaProve. Please Report this issue to the GeneaProve developers. If your GEDCOM data contains information you wish to keep private, you can use the script gedcom_anon.py to anonymize the data before you send it to us. 
None"

It is the "None" in the last line that puzzles me. Any idea where I should look to correct my input file myself, before I anonymise and send it to you? I am aware that you are not supporting Reunion, but I can live with that for now.

Thanks.

**Comment by briot** [comment]
> I imported via de command line version and had to try several times. Apparently I had missed 1 unrecognised tag (_UID inside FAM, although the web interface never mentioned that), then a few lines that were too long, all of which I corrected in the import file; finally some other tag related errors occurred (SUBM @SUB1@ reference). I removed or corrected all offending input lines. Finally I got a


Hello,

I am finally getting back to geneaprove a bit. I am not able to fix the issues you reported since
I do not have your GEDCOM file (or rather, as recommended by the importer, an anonymized
version of it, though gedcom_anon.py). That would really help.

I have lifted the restriction on the long lines, which most likely was the most painful issue in
your import and might have resulted in the errors later on.

I have also validated the _UID tag under FAM (geneaprove is intentionally overly restrictive
currently -- the GEDCOM standard says that all imported must accept the _... tags, but then
it means they would be silently ignored in the actual import and data would be lost, which is
not the goal here).

Please let me know if you are still interested in investigating geneaprove, and if it is possible
for you to send an anonymized gedcom

thanks
Emmanuel=

**Comment by oriste** [comment]
Hi Emmanuel,

Thanks for responding.
I had abandoned the project when I didn’t get a reply. At this moment I won’t have the time to pick it up again. I still like it a lot (better than anything else I found out there), but I’m just too tied up with other projects. Hopefully I will be able to revisit it at a later date, I’d love that.

Kindly, 

oriste
