### ISSUE TITLE
Deeper Pedigree seems to work for Stats, others, but All Persons still fails on max recursion error.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#42]
As stated above, clicking on `All Persons` yields a recursion error when very large database.

Using the `ManyMany...` gedcom I shared with you, the attached Stack trace is generated.

Note: I have not done a re-import since the deeper trees commit. Would that make a difference?

[Stack Trace for All Persons.log](https://github.com/briot/geneapro/files/2871377/Stack.Trace.for.All.Persons.log)

**Comment by briot** [comment]
> As stated above, clicking on All Persons yields a recursion error when very large database.
> Using the ManyMany... gedcom I shared with you, the attached Stack trace is genereated.
> Note: I have not done a re-import since the deeper trees commit. Would that make a difference?
> Stack Trace for All Persons.log


This bug is not directly in All Persons view, but related to computing custom color styles.
I am redoing this part so that users can create their own (so far it was in a python file). Right now,
that problem should be gone from All Persons, since it doesn’t use custom styles anymore.

The fix is fortunately easy (remove a recursion), so I’ll commit a fix shortly
